"""Views, one for each Insta485 page."""
from insta485.views.index import show_index
from insta485.views.user import show_user
from insta485.views.uploads import show_uploads
from insta485.views.post import show_post
from insta485.views.user import show_followers
from insta485.views.user import show_following
from insta485.views.user import post_following
from insta485.views.explore import show_explore
from insta485.views.accounts import show_login
from insta485.views.accounts import show_create
from insta485.views.accounts import show_accounts
from insta485.views.accounts import show_logout
from insta485.views.accounts import show_password
from insta485.views.accounts import show_delete
from insta485.views.accounts import show_edit
from insta485.views.likes import show_likes
from insta485.views.comments import show_comments
from insta485.views.post import show_posts
